### PR TITLE
YouTube Icon and Link fixes#7

### PR DESCRIPTION
**Pull request by ssgshubham**
Added YouTube Icon and Link of DSC JIIT YouTube channel

### CODE REVIEW

**Comment by ssgshubham** [comment]
Added "Videos" Section in Sidebar

**Comment by ssgshubham** [comment]
Added Instagram Icon and DSC JIIT Ig page and updated events page

**Comment by ssgshubham** [comment]
Added the Videos Page

**Comment by rishhavv** [comment]
good work!

**Pull request merged**
